### ISSUE TITLE
Markdown body content missing when accessing project pages through direct link

### ISSUE THREAD

**Issue by SFRL** [QMUL-MAT/gatsby-mat#19]
I have noticed that when I try to access a project page through the direct link (e.g. https://mat.qmul.ac.uk/projects/garden-of-forking-paths) it does not display the text defined in the body of the related markdown file. It only appears to use the frontmatter content (title, description, video etc.) which suggests that there might be an issue with the GraphQL query?

I might have a go at this sometime in future, if no one else has a good idea why this is happening?

**Comment by Nagasaki45** [comment]
Good catch @SFRL. Looks like this: https://github.com/gatsbyjs/gatsby/issues/10581. Will try to solve it tomorrow, or otherwise probably next weekend.

**Comment by Nagasaki45** [comment]
Yep, don't wrap an element that generates content from markdown, like the following example, with `<p>` tags:
```html
<div dangerouslySetInnerHTML={{__html: content}}></div>
```
